### ISSUE TITLE
App crashes on iOS

### ISSUE THREAD

**Issue by roipeker** [tuarua/Vibration-ANE#11]
Using debugger build or adhoc, after compile ipa with the provided ANE ( /native_extension/ane/VibrationANE.ane ) and the /Frameworks folder.

App can't be opened, crashes directly on device.

Using Intellij , iPhone7+, iOS 12.0, AIR 31.0.0.96

**Comment by roipeker** [comment]
I did run get_ios_dependencies.sh.
Yet I'm having my doubts that my internet is really unstable lately, and maybe some files could be corrupted. 

I'll get try again tomorrow from another location and keep you posted with the crash logs if it still crashes.

Thanks.

**Comment by tuarua** [comment]
This is how I package "Frameworks"

<img width="786" alt="image" src="https://user-images.githubusercontent.com/12083217/47120036-35be6480-d265-11e8-81a0-affb194d9a78.png">

Let me know. I was a bit blind with the Haptic + Taptic testing as I don't actually own an iPhone, just iPads which have no vibration built in.

The ANE code is actually very light - so do have a read.

https://github.com/tuarua/Vibration-ANE/blob/master/native_library/apple/VibrationANE/VibrationANE/SwiftController.swift

**Comment by roipeker** [comment]
It was indeed my internet connection dude, corrupted files :(

Thanks! **vibrate(id)**; **ImpactFeedbackGenerator** and **NotificationFeedbackGenerator**; works very well.

I couldn't make SelectionFeedbackGenerator to work though... I try adding some delays between "selectionChanged()" calls, but still, I get no feedback at all.
