### ISSUE TITLE
VibrationAne was not found for the target platform.

### ISSUE THREAD

**Issue by yooni126** [tuarua/Vibration-ANE#4]
I want to test your example project in ios and read your help step by step
now in Mac os, and air sdk 29 in intelij IDE  when I compile project I see this error : 

An implementation for native extension 'com.tuarua.VibrationANE' required by the application was not found for the target platform.

![capture](https://user-images.githubusercontent.com/3766387/40679936-c7c99cf4-6399-11e8-8a65-a427ed527acb.JPG)

![capture2](https://user-images.githubusercontent.com/3766387/40680019-06d5058c-639a-11e8-9f05-1bda7f369905.JPG)

**Comment by tuarua** [comment]
All working fine for me.

Please ensure the ANE is added under "Dependencies" tab - is not giving a broken path and is marked as an ANE.
![image](https://user-images.githubusercontent.com/12083217/40688655-d2ee4d58-6396-11e8-9965-646079f83bec.png)


Please correct the dependencies path 

![image](https://user-images.githubusercontent.com/12083217/40688488-326accc6-6396-11e8-98ad-728478010ed5.png)

The safest way to download the ANE and dependencies is using the get_ios_dependencies.sh bash script provided

**Comment by yooni126** [comment]
thank you but there is no vibrationAne.ANE in your repository!
I see only vibrationANE.swc
also I used bash script(get_ios_dependencies.sh) but it downloaded only framework files.
how can I get ANE file?

**Comment by yooni126** [comment]
thank you Tuarua  , you are one of my hero in Air developer world 👍 
now it works like a charm!
only I must set framework path to this for it working for me :

![capture](https://user-images.githubusercontent.com/3766387/40782778-a233bdfa-64f5-11e8-8f47-b00ae1970b76.JPG)
