### ISSUE TITLE
(Feature request) Implement haptic feedback api  ios

### ISSUE THREAD

**Issue by roipeker** [tuarua/Vibration-ANE#8]
Is it possible to include AudioServicesPlaySystemSound on iOS to make better use of the taptic engine? 
To improve UI experience using subtle vibrations on iphone6s and newer devices.

Reference:
https://medium.com/@sdrzn/make-your-ios-app-feel-better-a-comprehensive-guide-over-taptic-engine-and-haptic-feedback-724dec425f10

**Comment by tuarua** [comment]
Thanks for the link.
I will investigate and consider.

**Comment by tuarua** [comment]
Please check the latest version.
Haptic and Taptic support added.

**Comment by roipeker** [comment]
Closing ticket
